### ISSUE TITLE
add unreviewed review requests to counter

### ISSUE THREAD

**Issue by lukaselmer** [renuo/pull-requests-counter#5]
... if it is possible 😉 

![image](https://cloud.githubusercontent.com/assets/326935/21685378/a0d029b6-d361-11e6-8278-380637e18bf5.png)

**Comment by coorasse** [comment]
I checked the GitHub API and at the moment is not possible. 
I'll leave your issue open because I consider it an important feature and we'll come back to it when the APIs will provide this information.
In the meantime I got in touch with GitHub about this issue.

**Comment by coorasse** [comment]
There is something going on on Beta:

> You can fetch the list of reviews and review requests using these endpoints:
> 
> https://developer.github.com/v3/pulls/reviews/
> 
> https://developer.github.com/v3/pulls/review_requests/

Adding `Accept: application/vnd.github.black-cat-preview+json` allows us to fetch Beta APIs and so, also the review requests for a single issue. 
The problem is still that we do not have an API to retrieve all issues of which I am a reviewer.
